[package]
name = "gdrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
flate2 = "1.0.28"
indextree = "4.6.0"
quick-xml = "0.31.0"
thiserror = "1.0.56"
